# Run Component Governance to register all dependencies.

trigger:
  - main
  - romanlutz/cg_fix

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: pip install --upgrade setuptools pip
    name: UpgradePip

  - script: pip install --ignore-installed --dry-run --quiet --report ./component-detection-pip-report.json .
    name: GeneratePipReport
  
  - script: cat ./component-detection-pip-report.json
    name: ShowPipReport

  - task: ComponentGovernanceComponentDetection@0
    env:
      PIP_INDEX_URL: https://pypi.org/simple
