# Run Component Governance to register all dependencies.

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  # Component Governance does not support pyproject.toml yet.
  # For that reason, use toml-to-requirements to export the
  # dependencies into a requirements.txt file.
  - run: pip install toml-to-requirements

  - run: toml-to-req --toml-file pyproject.toml

  - task: ComponentGovernanceComponentDetection@0
