# Run Component Governance to register all dependencies.

trigger:
  - main
  - romanlutz/cg_fix

pool:
  vmImage: "ubuntu-latest"

steps:
  - name: Upgrade pip
    script: pip install --upgrade setuptools pip

  - name: Generate Pip Report
    script: pip install --ignore-installed --dry-run --quiet --report ./component-detection-pip-report.json .

  - task: ComponentGovernanceComponentDetection@0
