# Run Component Governance to register all dependencies.

trigger:
  - main
  - romanlutz/cg_fix

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: pip install --upgrade setuptools pip
    name: UpgradePip

  - script: pip install --ignore-installed --dry-run --quiet --report ./component-detection-pip-report.json .
    name: GeneratePipReport

  - task: ComponentGovernanceComponentDetection@0
