# Run Component Governance to register all dependencies.

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  # Component Governance does not support pyproject.toml yet.
  # For that reason, use toml-to-requirements to export the
  # dependencies into a requirements.txt file.
  - script: pip install --upgrade setuptools pip
    name: UpgradePip

  - script: pip install toml-to-requirements

  - script: toml-to-req --toml-file pyproject.toml

  - task: ComponentGovernanceComponentDetection@0
    env:
      PIP_INDEX_URL: https://pypi.python.org/simple
