# Run Component Governance to register all dependencies.

trigger:
  - main

# There are additional PR triggers for this that are configurable in ADO.

pool:
  vmImage: "ubuntu-latest"

steps:
  # Component Governance does not support pyproject.toml yet.
  # For that reason, use toml-to-requirements to export the
  # dependencies into a requirements.txt file.
  - script: pip install --upgrade setuptools pip
    name: UpgradePip

  - script: pip install toml-to-requirements

  - script: toml-to-req --toml-file pyproject.toml

  - task: ComponentGovernanceComponentDetection@0
    env:
      PIP_INDEX_URL: https://pypi.python.org/simple

  - task: notice@0
    displayName: Generate NOTICE file
    inputs:
      outputfile: $(System.DefaultWorkingDirectory)/obj/NOTICE
      outputformat: text

  - publish: $(System.DefaultWorkingDirectory)/obj/NOTICE
    artifact: NOTICE
