
# Builds the pyrit environment and runs integration tests

trigger:
- main

# There are additional PR triggers for this that are configurable in ADO.

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  displayName: Azure Key Vault - retrieve .env file secret
  inputs:
    azureSubscription: 'integration-test-service-connection'
    KeyVaultName: 'integration-test-env'
    SecretsFilter: 'pyrit-test'
    RunAsPreJob: false
- bash: python -c "import os; file = open('.env', 'w'); file.write(os.environ['PYRIT_TEST']); print(os.environ['PYRIT_TEST'][:146]); file.close()"
  env:
    PYRIT_TEST: $(pyrit-test)
- bash: ls -la
- bash: pip install --upgrade setuptools pip
- bash: pip install .[all]
- bash: make integration-test
