
# Builds the pyrit environment and runs integration tests

trigger:
- main

# There are additional PR triggers for this that are configurable in ADO.

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  displayName: Azure Key Vault - retrieve .env file secret
  inputs:
    azureSubscription: 'integration-test-service-connection'
    KeyVaultName: 'pyrit-environment'
    SecretsFilter: 'env-integration-test'
    RunAsPreJob: false
- bash: |
    python -c "
    import os;
    secret = os.environ.get('PYRIT_TEST_SECRET'); 
    if not secret: 
      raise ValueError('PYRIT_TEST_SECRET is not set'); 
    with open('.env', 'w') as file: 
      file.write(secret)"
  env:
    PYRIT_TEST_SECRET: $(env-integration-test)
  name: create env file
- bash: pip install --upgrade setuptools pip
  name: upgrade pip and setuptools before installing PyRIT
- bash: pip install .[all]
  name: install PyRIT
- bash: make integration-test
  name: run integration tests
- bash: rm -f .env
  name: clean up env file
