
# Builds the pyrit environment and runs integration tests

name: integration_tests

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - task: AzureKeyVault@2
#   displayName: Azure Key Vault - retrieve .env file secret
#   inputs:
#     azureSubscription: 'integration-test-service-connection'
#     KeyVaultName: 'integration-test-env'
#     SecretsFilter: 'pyrit-test-base64'
#     RunAsPreJob: false
- powershell: |
    $keyVaultName = "integration-test-service-connection"
    $secretNames = "pyrit-test"
    $secret = Get-AzKeyVaultSecret -VaultName $keyVaultName -Name $secretName
    $secretValue = $secret.SecretValue | ConvertFrom-SecureString -AsPlainText
    $secretValue | Set-Content -Path .env
- bash: ls -la
- bash: pip install --upgrade setuptools pip
- bash: pip install .[all]
- bash: make integration-test
