
# Builds the pyrit environment and runs integration tests

name: integration_tests

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  displayName: Azure Key Vault - retrieve .env file secret
  inputs:
    azureSubscription: 'integration-test-service-connection'
    KeyVaultName: 'integration-test-env'
    SecretsFilter: 'pyrit-test'
    RunAsPreJob: false
- bash: python -c "import os; file = open('.env', 'w'); file.write(os.environ['PYRIT_TEST'][:4])"
  env:
    PYRIT_TEST: $(pyrit-test)
- bash: ls -la
- bash: cat .env
- bash: pip install --upgrade setuptools pip
- bash: pip install .[all]
- bash: make integration-test
