
# Builds the pyrit environment and runs integration tests

name: integration_tests

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  displayName: Azure Key Vault - retrieve .env file secret
  inputs:
    azureSubscription: 'integration-test-service-connection'
    KeyVaultName: 'integration-test-env'
    SecretsFilter: 'pyrit-test-base64'
    RunAsPreJob: false
- bash: python -c "import os; print(os.environ['PYRIT_TEST_BASE64'][:4])"
  env:
    PYRIT_TEST_BASE64: $(pyrit-test-base64)
- bash: ls -la
- bash: cat .env
- bash: cat .env | base64 -d > .env
- bash: ls -la
- bash: pip install --upgrade setuptools pip
- bash: pip install .[all]
- bash: make integration-test
