name: PoliCheck

on:
  workflow_dispatch:

jobs:
  PoliCheck:
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
      - name: List files
        run: |
          for %%f in ( "$(Build.SourcesDirectory)\*" ) do @echo %%f
      - name: Run PoliCheck
        uses: actions/checkout@v2
      - name: PoliCheck
        run: |
          PoliCheck.exe -t $(Build.SourcesDirectory)/ -r $(Build.SourcesDirectory)/artifacts/result/PoliCheck.xml -o tools/SecurityTools/PoliCheckFileExtensions.xml
      - name: Save artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
