# PoliCheck

trigger:
- main

pool:
  vmImage: windows-latest

pr:
  branches:
    include:
      - main

jobs:
  - job: PoliCheck
    timeoutInMinutes: 120
    steps:
        - task: CmdLine@2
          displayName: 'List files'
          inputs:
            script: |
              for %%f in ( "$(Build.SourcesDirectory)\*" ) do @echo %%f
        - task: PoliCheck@2
          displayName: Run PoliCheck
          inputs:
            targetArgument: $(Build.SourcesDirectory)/
            result: $(Build.SourcesDirectory)/artifacts/result/PoliCheck.xml
            optionsFTPATH: tools/SecurityTools/PoliCheckFileExtensions.xml
        - task: PublishPipelineArtifact@0
          displayName: Save artifacts
          condition: succeededOrFailed()
          inputs:
            artifactName: artifacts
            targetPath: artifacts
