import { makeStyles, tokens } from '@fluentui/react-components'

export const useMessageListStyles = makeStyles({
  root: {
    flex: 1,
    overflowY: 'auto',
    padding: tokens.spacingVerticalXXL,
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalL,
  },
  message: {
    display: 'flex',
    gap: tokens.spacingHorizontalM,
    maxWidth: '800px',
    alignSelf: 'flex-start',
  },
  userMessage: {
    alignSelf: 'flex-end',
    flexDirection: 'row-reverse',
  },
  messageContent: {
    backgroundColor: tokens.colorNeutralBackground3,
    padding: tokens.spacingVerticalM,
    borderRadius: tokens.borderRadiusMedium,
    flex: 1,
  },
  userMessageContent: {
    backgroundColor: tokens.colorBrandBackground,
  },
  messageText: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  messageFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: tokens.spacingVerticalXS,
    gap: '15px',
  },
  timestamp: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
  },
  role: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
    fontStyle: 'italic',
  },
  loadingEllipsis: {
    fontSize: tokens.fontSizeBase500,
    animationName: {
      '0%': { opacity: '0.3' },
      '50%': { opacity: '1' },
      '100%': { opacity: '0.3' },
    },
    animationDuration: '1.5s',
    animationIterationCount: 'infinite',
  },
  attachmentsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
    marginTop: tokens.spacingVerticalS,
  },
  imageContainer: {
    position: 'relative' as const,
    display: 'inline-block',
    maxWidth: '400px',
    maxHeight: '400px',
    minWidth: '100px',
    minHeight: '60px',
  },
  imageSpinner: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  attachmentPreview: {
    maxWidth: '400px',
    maxHeight: '400px',
    borderRadius: tokens.borderRadiusMedium,
    objectFit: 'contain',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  attachmentPreviewHidden: {
    maxWidth: '400px',
    maxHeight: '400px',
    borderRadius: tokens.borderRadiusMedium,
    objectFit: 'contain',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    visibility: 'hidden' as const,
    width: 0,
    height: 0,
  },
  videoPreview: {
    maxWidth: '400px',
    maxHeight: '300px',
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  attachmentFile: {
    padding: tokens.spacingVerticalS,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    gap: tokens.spacingVerticalM,
  },
  errorContainer: {
    marginTop: tokens.spacingVerticalS,
  },
  mediaActions: {
    display: 'flex',
    gap: tokens.spacingHorizontalXXS,
    marginTop: tokens.spacingVerticalXXS,
  },
  messageActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: tokens.spacingHorizontalXXS,
    marginTop: tokens.spacingVerticalS,
  },
  reasoningContainer: {
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    marginBottom: tokens.spacingVerticalS,
  },
  reasoningLabel: {
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: tokens.spacingVerticalXXS,
  },
  reasoningText: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    lineHeight: tokens.lineHeightBase200,
  },
  originalSection: {
    marginBottom: tokens.spacingVerticalS,
    opacity: 0.6,
  },
  originalText: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    color: tokens.colorNeutralForeground3,
  },
  sectionLabel: {
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: tokens.spacingVerticalXXS,
    cursor: 'default',
  },
  sectionDivider: {
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    marginTop: tokens.spacingVerticalS,
    marginBottom: tokens.spacingVerticalS,
  },
  convertedLabel: {
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorBrandForeground1,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: tokens.spacingVerticalXXS,
    cursor: 'default',
  },
})
