# Builds the pyrit environment and runs integration tests

name: integration_tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "release/**"
  workflow_dispatch:
  schedule:
    # daily at midnight (Pacific Time) in UTC
    - cron: "0 8 * * *"

concurrency:
  # This ensures after each commit the old jobs are cancelled and the new ones
  # run instead.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main-job:
    environment: integration-tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11", "3.12"]
        package_name: ["pyrit"]
        package_extras: ["all"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: test secret
        run: |
          echo ${{ env.SUPER_SECRET }}
          echo ${{ secrets.TEST_SECRET }}
          echo ${{ secrets.GITHUB_TOKEN }}
          echo '${{ env.SUPER_SECRET }}'
          echo '${{ secrets.TEST_SECRET }}'
          echo '${{ secrets.GITHUB_TOKEN }}'
        env:
          SUPER_SECRET: ${{ secrets.TEST_SECRET }}
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install setuptools and pip
        run: pip install --upgrade setuptools pip
      - name: Install PyRIT with pip
        run: pip install .[${{ matrix.package_extras }}]
      - name: Run unit tests with code coverage
        run: make test-cov-xml
